# Generated by Django 5.2.7 on 2026-09-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='user_profile.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id', ''), _negated=True), fields=('tenant', 'employee_id'), name='unique_staff_employee_per_school'),
        ),
    ]
