# Generated by Django 5.2.7 on 2026-09-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_staffprofile_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user_profile__first_name'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
