# Generated by Django 5.2.7 on 2026-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_staff_type_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, choices=[('plus_two', '+2'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('mphil', 'MPhil'), ('phd', 'PhD'), ('other', 'Other')], max_length=30),
        ),
    ]
