# Generated by Django 5.2.7 on 2026-09-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_staff_created_at_alter_staff_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('hod', 'Head of Department'), ('librarian', 'Librarian'), ('accountant', 'Accountant'), ('admin', 'Admin Staff'), ('support', 'Support Staff'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
