# Generated by Django 5.2.7 on 2026-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staff_designation'),
        ('tenants', '0007_tenant_slug'),
        ('user_profile', '0006_userprofile_gender_userprofile_nationality'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['tenant', 'designation', 'is_active'], name='staff_staff_tenant__a1ddcf_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['tenant', 'department', 'is_active'], name='staff_staff_tenant__3768d4_idx'),
        ),
    ]
