# Generated by Django 5.2.7 on 2026-09-26 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_school_classes'),
        ('finance', '0002_copy_fees_data'),
        ('staff', '0009_alter_staff_designation'),
        ('students', '0005_alter_exam_created_at_alter_exam_updated_at_and_more'),
        ('tenants', '0007_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'expense_date'], name='finance_exp_tenant__3c8047_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'category', 'expense_date'], name='finance_exp_tenant__0b1232_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='finance_fee_tenant__911f11_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['tenant', 'invoice', 'payment_date'], name='finance_fee_tenant__456f28_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['tenant', 'month'], name='finance_pay_tenant__9a0703_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['tenant', 'status', 'month'], name='finance_pay_tenant__a05479_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='finance_stu_tenant__8bec27_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['tenant', 'student', 'due_date'], name='finance_stu_tenant__114db2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['tenant', 'academic_year', 'due_date'], name='finance_stu_tenant__2461ac_idx'),
        ),
    ]
