# Generated by Django 5.2.7 on 2026-09-21 16:06

import uuid
from django.db import migrations, models

from utils.migrations import AddUUIDField


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        AddUUIDField(
            model_name='academicyear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='class',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='section',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='teacherassignment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='timetableentry',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
