# Generated by Django 5.2.7 on 2026-09-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_academicyear_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes that offer this subject (a subject spans many grades).', related_name='subjects', to='academics.class'),
        ),
    ]
