# Generated by Django 5.2.7 on 2026-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_school_classes'),
        ('students', '0005_alter_exam_created_at_alter_exam_updated_at_and_more'),
        ('tenants', '0007_tenant_slug'),
        ('user_profile', '0006_userprofile_gender_userprofile_nationality'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'academic_year', 'start_date'], name='students_ex_tenant__b062ec_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['tenant', 'exam'], name='students_ex_tenant__dc60ab_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['tenant', 'student'], name='students_ex_tenant__090339_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'school_class', 'section'], name='students_st_tenant__909545_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'admission_date'], name='students_st_tenant__b05b97_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['tenant', 'date'], name='students_st_tenant__b34464_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['tenant', 'section', 'date'], name='students_st_tenant__7acc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['tenant', 'status', 'date'], name='students_st_tenant__3e5227_idx'),
        ),
    ]
