# Generated by Django 5.2.7 on 2026-09-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_alter_librarymember_student'),
        ('user_profile', '0002_parent_uuid_student_uuid_studentguardian_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentguardian',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentGuardian',
        ),
    ]
