# Generated by Django 5.2.7 on 2026-09-21 16:06

import uuid
from django.db import migrations, models

from utils.migrations import AddUUIDField


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_department'),
    ]

    operations = [
        AddUUIDField(
            model_name='department',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='schoolsettings',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
