# Generated by Django 5.2.7 on 2026-09-22 02:18

from django.db import migrations, models


def backfill_updated_at(apps, schema_editor):
    """Old rows kept a NULL ``modified_at``; seed ``updated_at`` from ``created_at``
    before the column is made NOT NULL and auto_now-maintained."""
    for model in (
        apps.get_model("tenants", "Tenant"),
        apps.get_model("tenants", "Department"),
    ):
        table = model._meta.db_table
        schema_editor.execute(
            f"UPDATE {table} SET updated_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_department_modified_at_tenant_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]