# Generated by Django 5.2.7 on 2026-09-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_department_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('primary', 'Primary'), ('lower_secondary', 'Lower Secondary'), ('secondary', 'Secondary'), ('administration', 'Administration'), ('library', 'Library'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
