"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config  # AutoConfig: reads the nearest .env (repo root), falls back to os.environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from .env / environment. NOTE: names are DJANGO_-prefixed on purpose — a bare
# `DEBUG` is exported by some shells/tools (e.g. `DEBUG=release`) and would collide
# through os.environ, which decouple checks before .env.
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-n(k*p7g!tk9%80s(u64aqcpmj4p%$$+f$_0=(715@%yiv$jyoc')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [h.strip() for h in config('DJANGO_ALLOWED_HOSTS', default='').split(',') if h.strip()]
TENANT_ROOT_DOMAIN = config('TENANT_ROOT_DOMAIN', default='')
TENANT_PLATFORM_HOSTS = [
    h.strip() for h in config(
        'TENANT_PLATFORM_HOSTS',
        default='localhost,127.0.0.1,testserver'
    ).split(',') if h.strip()
]

AUTH_USER_MODEL = 'user_account.UserAccount'

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    # Serves static files through WhiteNoise even under runserver (bypasses the
    # staticfiles app so dev and prod behave the same).
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # Enables the outstanding-token/blacklist tables so refresh tokens can be
    # revoked (used by logout and by refresh-token rotation).
    'rest_framework_simplejwt.token_blacklist',
    'apps.tenants',
    'apps.core',
    'apps.user_account',
    'apps.user_profile',
    'apps.staff',
    'apps.subscription',
    'apps.academics',
    'apps.communication',
    'apps.students',
    'apps.parents',
    'apps.teachers',
    'apps.library',
    'apps.finance',
    'apps.reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must be directly after SecurityMiddleware (whitenoise docs).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.tenants.middleware.TenantMiddleware',
    # Must come BEFORE your custom middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Your custom JWT +(AFTER auth)
    # Custom: copy JWT from cookie to Authorization header (so DRF SimpleJWT works)
    'apps.user_account.middleware.CustomJWTMiddleware',
    'apps.user_account.middleware.CookieJWTCSRFMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "auth_login": config("AUTH_LOGIN_THROTTLE", default="5/min"),
        "auth_refresh": config("AUTH_REFRESH_THROTTLE", default="20/min"),
    },
    "DEFAULT_PAGINATION_CLASS": "utils.paginations.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
}



ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Resolution order: real environment variable > .env file > default.
        'NAME': config('DB_NAME', default='school_saas'),
        'USER': config('DB_USER', default='school_saas'),
        'PASSWORD': config('DB_PASSWORD', default='school_saas'),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic target — served by WhiteNoise in production (see STORAGES).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User uploads (Tenant.logo, StudentDocument.file).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compression + hashing; falls back gracefully under runserver.
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def _csv_setting(name, default):
    """Comma-separated environment variable -> clean list of origins."""
    return [o.strip() for o in config(name, default=default).split(',') if o.strip()]


# Cross-origin access for the browser app. Same-origin proxy deployments don't
# need it, but a split deployment (frontend on :3000, API on :8000 / a domain) does.
CORS_ALLOWED_ORIGINS = _csv_setting(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000'
)
CORS_ALLOW_CREDENTIALS = True

# Needed so the Django admin's CSRF check accepts the deployed origin.
CSRF_TRUSTED_ORIGINS = _csv_setting(
    'CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:8000'
)


from datetime import timedelta
# cookie names
JWT_ACCESS_COOKIE = "access"
JWT_REFRESH_COOKIE = "refresh"
JWT_CSRF_COOKIE = "csrf_token"
JWT_COOKIE_SAMESITE = config('JWT_COOKIE_SAMESITE', default='Lax')
JWT_ACCESS_COOKIE_AGE = 30 * 60
JWT_REFRESH_COOKIE_AGE = 7 * 24 * 60 * 60
# Cookies must be Secure in production (HTTPS-only); reads settings dynamically.
JWT_COOKIE_SECURE = not DEBUG

# Short-lived access token + rotating refresh tokens. Rotation blacklists the
# presented refresh token (token_blacklist app), so a stolen refresh token dies
# on first reuse.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "UPDATE_LAST_LOGIN": True,
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# ---------------------------------------------------------------------------
# Production hardening (Django deployment checklist).
# Every item is gated on DEBUG so local development keeps working unchanged.
# Run `python manage.py check --deploy` with DJANGO_DEBUG=False to verify.
# ---------------------------------------------------------------------------
if not DEBUG:
    # Terminate TLS at the reverse proxy; trust its forwarded-proto header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('DJANGO_SSL_REDIRECT', default=True, cast=bool)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'
