# Generated by Django 5.2.7 on 2026-09-21 16:06

import uuid
from django.db import migrations, models

from utils.migrations import AddUUIDField


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_announcement_message_notification'),
    ]

    operations = [
        AddUUIDField(
            model_name='announcement',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='studentpost',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='teacherannouncement',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
