# Generated by Django 5.2.7 on 2026-09-22 02:18

from django.db import migrations, models


def backfill_updated_at(apps, schema_editor):
    for model_name in (
        "Announcement",
        "Message",
        "Notification",
        "StudentPost",
        "TeacherAnnouncement",
    ):
        model = apps.get_model("communication", model_name)
        table = model._meta.db_table
        schema_editor.execute(
            f"UPDATE {table} SET updated_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_announcement_modified_at_message_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='studentpost',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='teacherannouncement',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='teacherannouncement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]