# Generated by Django 5.2.7 on 2026-09-22 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_remove_announcement_modified_at_and_more'),
        ('students', '0005_alter_exam_created_at_alter_exam_updated_at_and_more'),
        ('teachers', '0009_alter_teacher_class_teacher_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpost',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_posts', to='students.student'),
        ),
        migrations.AlterField(
            model_name='teacherannouncement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_announcements', to='teachers.teacher'),
        ),
    ]
