# Generated by Django 5.2.7 on 2026-09-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_studentpost_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='studentpost',
            options={'verbose_name': 'Student Post', 'verbose_name_plural': 'Student Posts'},
        ),
        migrations.AlterModelOptions(
            name='teacherannouncement',
            options={'verbose_name': 'Teacher Announcement', 'verbose_name_plural': 'Teacher Announcements'},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
    ]
