# Generated by Django 5.2.7 on 2026-09-26 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_alter_announcement_options_alter_message_options_and_more'),
        ('tenants', '0007_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['tenant', 'target_audience', 'created_at'], name='communicati_tenant__604856_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'recipient', 'is_read', 'created_at'], name='communicati_tenant__bf5ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'sender', 'created_at'], name='communicati_tenant__737214_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'user', 'is_read', 'created_at'], name='communicati_tenant__c30eeb_idx'),
        ),
    ]
