# Generated by Django 5.2.7 on 2026-09-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
    ]
