# Generated by Django 5.2.7 on 2026-09-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_uuid_class_uuid_section_uuid_and_more'),
        ('teachers', '0006_move_duplicate_teacher_fields_to_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='homeroom_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teachers', to='academics.section'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_weekly_periods',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teacher',
            name='primary_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_teachers', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
