# Generated by Django 5.2.7 on 2026-09-22 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_academicyear_created_at_and_more'),
        ('teachers', '0008_rename_homeroom_section_teacher_class_teacher_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to='academics.section'),
        ),
    ]
