# Generated by Django 5.2.7 on 2026-09-26 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teacher_class_teacher_section'),
        ('tenants', '0007_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='teachers_le_tenant__161987_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'teacher', 'created_at'], name='teachers_le_tenant__65108b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['tenant', 'date'], name='teachers_te_tenant__80378d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['tenant', 'teacher', 'date'], name='teachers_te_tenant__6a7e26_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['tenant', 'status', 'date'], name='teachers_te_tenant__2630da_idx'),
        ),
    ]
