# Generated by Django 5.2.7 on 2026-09-21 15:45

import apps.user_account.managers as user_account_managers
from django.db import migrations, models


def copy_names_to_profiles(apps, schema_editor):
    """Preserve existing first_name/last_name before the columns are dropped.

    Personal names now live on ``user_profile.UserProfile``; every account
    that carried a name gets (or reuses) a profile row so ``get_full_name()``
    keeps returning the same value after the upgrade.
    """
    UserAccount = apps.get_model('user_account', 'UserAccount')
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    for user in UserAccount.objects.all().iterator():
        if not (user.first_name or user.last_name):
            continue
        UserProfile.objects.get_or_create(
            user_account=user,
            defaults={'first_name': user.first_name, 'last_name': user.last_name},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['username'], 'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', user_account_managers.UserAccountManager()),
            ],
        ),
        # Preserve existing names BEFORE the columns are dropped.
        migrations.RunPython(copy_names_to_profiles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
