# Generated by Django 5.2.7 on 2026-09-21 16:06

import uuid
from django.db import migrations, models

from utils.migrations import AddUUIDField


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_useraccount_options_alter_useraccount_managers_and_more'),
    ]

    operations = [
        AddUUIDField(
            model_name='tenantmembership',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        AddUUIDField(
            model_name='useraccount',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
