# Generated by Django 5.2.7 on 2026-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_remove_useraccount_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
