# Generated by Django 5.2.7 on 2026-09-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_department_level'),
        ('user_account', '0005_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'role', 'is_active'], name='user_accoun_tenant__a9993f_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='user_accoun_user_id_d1a74f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='unique_user_tenant_membership'),
        ),
    ]
