# Generated by Django 5.2.7 on 2026-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_slug'),
        ('user_account', '0007_useraccount_username_blank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='user_accoun_tenant__1f5bb9_idx'),
        ),
    ]
