# Generated by Django 5.2.7 on 2025-11-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE academics_course (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(100) NOT NULL,
                code VARCHAR(20) NOT NULL UNIQUE,
                description TEXT,
                created_at DATETIME NOT NULL,
                organization_id INTEGER NOT NULL REFERENCES accounts_organization(id) DEFERRABLE INITIALLY DEFERRED,
                created_by_id INTEGER REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED
            );
            CREATE TABLE academics_subject (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(100) NOT NULL,
                course_id INTEGER NOT NULL REFERENCES academics_course(id) DEFERRABLE INITIALLY DEFERRED,
                teacher_id INTEGER REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED,
                created_at DATETIME NOT NULL,
                organization_id INTEGER NOT NULL REFERENCES accounts_organization(id) DEFERRABLE INITIALLY DEFERRED
            );
            CREATE TABLE academics_studentrecord (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                grade VARCHAR(2),
                remarks TEXT,
                created_at DATETIME NOT NULL,
                course_id INTEGER NOT NULL REFERENCES academics_course(id) DEFERRABLE INITIALLY DEFERRED,
                organization_id INTEGER NOT NULL REFERENCES accounts_organization(id) DEFERRABLE INITIALLY DEFERRED,
                student_id INTEGER NOT NULL REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS academics_course;
            DROP TABLE IF EXISTS academics_subject;
            DROP TABLE IF EXISTS academics_studentrecord;
            """
        )
    ]
