# Generated by Django 5.2.7 on 2026-09-22 02:18

from django.db import migrations, models


def backfill_updated_at(apps, schema_editor):
    model = apps.get_model("subscription", "Plan")
    table = model._meta.db_table
    schema_editor.execute(
        f"UPDATE {table} SET updated_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_plan_modified_at_alter_plan_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]