# Generated by Django 5.2.7 on 2026-09-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_plan_modified_at_plan_updated_at'),
        ('tenants', '0006_alter_department_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'is_active'], name='subscriptio_tenant__e06277_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'is_active'], name='subscriptio_plan_id_02164f_idx'),
        ),
    ]
