# Generated by Django 5.2.7 on 2026-09-23 10:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_plan_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('staff', 'Staff'), ('parents', 'Parents'), ('academics', 'Academics'), ('communication', 'Communication'), ('finance', 'Finance'), ('library', 'Library'), ('reports', 'Reports')], help_text="Stable machine identifier, e.g. 'finance'.", max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='reports_tier',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', help_text='Depth of the Reports feature granted by this plan.', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_students',
            field=models.PositiveIntegerField(default=100, help_text='Maximum students this plan allows (a limit, not a feature).'),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Features this plan grants its subscribers.', related_name='plans', to='subscription.feature'),
        ),
    ]
