# Generated by Django 5.2.7 on 2026-09-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_feature_plan_reports_tier_alter_plan_max_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='reports_tier',
        ),
    ]
