# Generated by Django 5.2.7 on 2026-09-23 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_create_free_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('method', models.CharField(choices=[('online', 'Online'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash')], default='online', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank/online order reference for this payment.', max_length=100)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_renewal', models.BooleanField(default=False, help_text='True when this payment renewed or upgraded an existing subscription.')),
                ('plan', models.ForeignKey(help_text='Plan this payment was charged for (price snapshot).', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscription.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['status', 'payment_date'], name='subscriptio_status_25315d_idx'), models.Index(fields=['subscription', 'is_renewal'], name='subscriptio_subscri_9024e6_idx')],
            },
        ),
    ]
