# Generated by Django 5.2.7 on 2026-09-24 03:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_backfill_subscription_payments'),
        ('tenants', '0006_alter_department_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('request_type', models.CharField(choices=[('renew', 'Renew'), ('change_plan', 'Change Plan')], help_text='What the school is asking for: renew the current plan or switch plan.', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional note from the school to the platform admin.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Reply from the platform admin, e.g. rejection reason.')),
                ('plan', models.ForeignKey(blank=True, help_text='Target plan for a change-plan request (renew keeps the current plan).', null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.plan')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Super admin who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subscription Request',
                'verbose_name_plural': 'Subscription Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='subscriptio_tenant__124164_idx'), models.Index(fields=['status', 'created_at'], name='subscriptio_status_0d8248_idx')],
            },
        ),
    ]
